### PR TITLE
WebSocket subscriptions

### LINKED ISSUE #5: Enable WebSocket subscriptions to inboxes
Depends on #1.

Clients should be able to subscribe to inboxes using WebSocket so that they get push messages directly after a new notifications arrives.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #5

### CODE REVIEW

**Comment by literarymachine** [comment]
@dr0i @fsteeg this one is actually a bit tricky to test interactively because you cannot use curl for WebSockets. One approach would be to first start the server
```
$ npm start

> skohub-pubsub@0.1.0 start /home/fo/.local/src/skohub-pubsub
> node index.js

Publish-subscribe server listening on port 3000!
```
and the publisher:
```
$ node node src/publisher.js
Publisher listening { address: '127.0.0.1', family: 'IPv4', port: 42936 }
```
Then you can use the Javascript console of your browser to subscribe to a topic of that publisher (exchange the port for the one reported by your publisher):
```
const ws = new WebSocket('ws://localhost:3000')
ws.onmessage = console.log
ws.send(JSON.stringify({mode: 'subscribe', topic: 'http://127.0.0.1:42936/topic'}))
```
At this point you should receive a message confirming the subscription. Now you can use curl to publish as usual:
```
$ curl -i "localhost:3000/inbox?target=http://127.0.0.1:42936/topic" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'
HTTP/1.1 202 Accepted
```
The messages should be logged in your browser console.

**Comment by literarymachine** [comment]
You can now also test this with https://github.com/hbz/skohub-deck/pull/2.

**Review by fsteeg — APPROVED** [review]
Browser console:

`message { target: WebSocket, isTrusted: true, data: "{\"mode\":\"confirm\",\"topic\":\"http://127.0.0.1:38857/topic\"}", origin: "ws://localhost:3000", lastEventId: "", ports: Restricted, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, … }`

Command line:

`curl -i "localhost:3000/inbox?target=http://127.0.0.1:38857/topic" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'`
`HTTP/1.1 202 Accepted`

**Comment by dr0i** [comment]
I had to use `ws.onopen = () => ws.send(JSON.stringify( ...` to bring the Javascript in the "console of your browser to subscribe to a topic of that publisher " to work.

**Review by dr0i — APPROVED** [review]

**Pull request merged**
