### PR TITLE
Implement LDN inboxes

### LINKED ISSUE #1: LDN Inboxes for GND entities
To notify about corrections, backlinks or else we need an LDN inbox for every GND entity.

Eventually, the inbox URLs (however they will look like) will be added to lobid-gnd (not part of this issue), e.g.:

```json
{
   "@context":"http://lobid.org/gnd/context.jsonld",
   "id":"http://d-nb.info/gnd/4219521-4",
   "inbox":"https://skohub.io/lobid-gnd?id=4219521-4"
}
```

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #1

### CODE REVIEW

**Comment by literarymachine** [comment]
@acka47 I forked the repo in order to set up https://travis-ci.org/literarymachine/skohub-pubsub. Could you enable Travis for https://travis-ci.org/hbz/skohub-pubsub?

**Comment by acka47** [comment]
I activated the repo. Hope that is enough.

**Comment by fsteeg** [comment]
+1

I was able to reproduce the README steps.

One step is missing: `cd skohub-pubsub` after cloning.

In our lobid workflow we open branches in the main repo, not our forks. Here, I could have then just pushed the additional step into the README in this pull request's branch.

**Comment by literarymachine** [comment]
> In our lobid workflow we open branches in the main repo, not our forks. Here, I could have then just pushed the additional step into the README in this pull request's branch.

Yes, I just forked to get Travis up and running. See https://github.com/hbz/skohub-pubsub/pull/4#issuecomment-472754413.

**Pull request merged**
